#!/usr/bin/env bash
# Installs the Claude Harness rules/skills/memory pack + statusline into
# ~/.claude. Idempotent — safe to re-run after `git pull`.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLAUDE_DIR="${CLAUDE_HARNESS_TARGET:-$HOME/.claude}"
PACK_DIR="$CLAUDE_DIR/claude-harness"
CLAUDE_MD="$CLAUDE_DIR/CLAUDE.md"
MARKER_START="<!-- claude-harness:managed:start (auto-generated by install.sh — do not hand-edit; re-run install.sh to update) -->"
MARKER_END="<!-- claude-harness:managed:end -->"

echo "[claude-harness] installing from $REPO_DIR into $CLAUDE_DIR"

# --- 1. Pack files: namespaced, never touch ~/.claude/skills or ~/.claude/memory directly ---
mkdir -p "$PACK_DIR"
rm -rf "$PACK_DIR/rules" "$PACK_DIR/skills" "$PACK_DIR/memory"
cp -r "$REPO_DIR/rules" "$PACK_DIR/rules"
cp -r "$REPO_DIR/skills" "$PACK_DIR/skills"
cp -r "$REPO_DIR/memory" "$PACK_DIR/memory"
cp "$REPO_DIR/WORKFLOW.md" "$PACK_DIR/WORKFLOW.md"
echo "[claude-harness] pack files synced to $PACK_DIR"

# --- 2. Statusline: dictated path, safe to copy directly ---
mkdir -p "$CLAUDE_DIR"
if [ ! -f "$CLAUDE_DIR/statusline.sh" ] || ! cmp -s "$REPO_DIR/statusline/statusline.sh" "$CLAUDE_DIR/statusline.sh"; then
  cp "$REPO_DIR/statusline/statusline.sh" "$CLAUDE_DIR/statusline.sh"
  chmod +x "$CLAUDE_DIR/statusline.sh"
  echo "[claude-harness] statusline.sh installed/updated at $CLAUDE_DIR/statusline.sh"
else
  echo "[claude-harness] statusline.sh already up to date"
fi

if [ -f "$CLAUDE_DIR/settings.json" ] && grep -q '"statusLine"' "$CLAUDE_DIR/settings.json"; then
  echo "[claude-harness] settings.json already has a statusLine block — leaving it alone"
else
  cat <<EOF
[claude-harness] settings.json has no statusLine block. Add manually (see statusline/README.md):
  "statusLine": { "type": "command", "command": "bash \"$CLAUDE_DIR/statusline.sh\"", "refreshInterval": 60 }
EOF
fi

# --- 3. Managed pointer block in CLAUDE.md (Claude Code's always-loaded file) ---
# Does NOT copy security-invariants.md verbatim: if your CLAUDE.md already has
# hand-written security rules, dedupe them against rules/security-invariants.md
# yourself first — this installer never overwrites your prose, only its own
# marked block.
COMMIT="$(cd "$REPO_DIR" && git rev-parse --short HEAD 2>/dev/null || echo unknown)"
BLOCK_FILE="$(mktemp)"
{
  echo "$MARKER_START"
  echo "## Claude Harness (installed from $REPO_DIR @ $COMMIT)"
  echo
  echo "- Security invariants (always-on, every session/surface — read this alongside this file): \`$PACK_DIR/rules/security-invariants.md\`"
  echo "- Engineering rules (YAGNI ladder, debugging, review, deps, perf, commit lifecycle): \`$PACK_DIR/rules/engineering.md\`"
  echo "- Design lane (triggered on UI/UX task shape): \`$PACK_DIR/rules/design-lane.md\`"
  echo "- Skills manifest (install/version source of truth): \`$PACK_DIR/skills/manifest.yaml\`"
  echo "- Memory spec (session checkpoints + mistake-memory; hooks are spec-only, not shipped yet): \`$PACK_DIR/memory/SPEC.md\`"
  echo "- Workflow loop (Understand -> Plan -> Build -> Verify -> Security-if-needed): \`$PACK_DIR/WORKFLOW.md\`"
  echo "$MARKER_END"
} > "$BLOCK_FILE"

touch "$CLAUDE_MD"
cp "$CLAUDE_MD" "$CLAUDE_MD.bak.$(date +%Y%m%d%H%M%S)"

if grep -qF "$MARKER_START" "$CLAUDE_MD"; then
  TMP="$(mktemp)"
  awk -v start="$MARKER_START" -v end="$MARKER_END" -v blockfile="$BLOCK_FILE" '
    $0 == start { while ((getline line < blockfile) > 0) print line; skip=1; next }
    $0 == end { skip=0; next }
    skip { next }
    { print }
  ' "$CLAUDE_MD" > "$TMP"
  mv "$TMP" "$CLAUDE_MD"
  echo "[claude-harness] updated managed block in $CLAUDE_MD"
else
  { cat "$CLAUDE_MD"; echo; cat "$BLOCK_FILE"; } > "$CLAUDE_MD.new"
  mv "$CLAUDE_MD.new" "$CLAUDE_MD"
  echo "[claude-harness] appended managed block to $CLAUDE_MD"
fi
rm -f "$BLOCK_FILE"

echo "[claude-harness] done. Pack: $PACK_DIR | Managed block: $CLAUDE_MD"
