#!/usr/bin/env bash
# Installs the Claude Harness rules/skills/memory pack + statusline into
# ~/.claude. Idempotent — safe to re-run after `git pull`.
#
# Usage: ./install.sh [--with-memory-hooks]
#   --with-memory-hooks   Also install the session-checkpoint hooks (see
#                          memory/SPEC.md). Opt-in, default off: these fire on
#                          every single Edit/Write once wired, and this
#                          installer never auto-edits settings.json — you
#                          paste the printed hook config in yourself. Once
#                          installed with this flag, a later plain `./install.sh`
#                          (no flag) does NOT remove them — there is no
#                          implicit uninstall.
set -euo pipefail

WITH_MEMORY_HOOKS=0
for arg in "$@"; do
  case "$arg" in
    --with-memory-hooks) WITH_MEMORY_HOOKS=1 ;;
  esac
done

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLAUDE_DIR="${CLAUDE_HARNESS_TARGET:-$HOME/.claude}"
PACK_DIR="$CLAUDE_DIR/claude-harness"
CLAUDE_MD="$CLAUDE_DIR/CLAUDE.md"

# On Git Bash, $HOME/PACK_DIR/etc. are POSIX-style (/c/Users/...). That's fine
# for this script's own file operations, but any path we WRITE into CLAUDE.md
# or print as a settings.json snippet is consumed by native node.exe / Claude
# Code itself, which does not understand /c/... paths (confirmed directly:
# native node.exe fails "Cannot find module" on a POSIX-style require path).
# Use drive-letter form for everything user-facing/machine-facing; falls back
# to the original path unchanged on platforms without `pwd -W` (macOS/Linux,
# where this distinction doesn't exist anyway).
win_path() {
  local p="$1" w
  w=$(cd "$p" 2>/dev/null && pwd -W 2>/dev/null) || true
  if [ -n "$w" ]; then echo "$w"; else echo "$p"; fi
}
MARKER_START="<!-- claude-harness:managed:start (auto-generated by install.sh — do not hand-edit; re-run install.sh to update) -->"
MARKER_END="<!-- claude-harness:managed:end -->"

echo "[claude-harness] installing from $REPO_DIR into $CLAUDE_DIR"

# --- 1. Pack files: namespaced, never touch ~/.claude/skills or ~/.claude/memory directly ---
mkdir -p "$PACK_DIR" "$PACK_DIR/memory"
rm -rf "$PACK_DIR/rules" "$PACK_DIR/skills" "$PACK_DIR/memory/templates"
cp -r "$REPO_DIR/rules" "$PACK_DIR/rules"
cp -r "$REPO_DIR/skills" "$PACK_DIR/skills"
cp "$REPO_DIR/memory/SPEC.md" "$PACK_DIR/memory/SPEC.md"
cp -r "$REPO_DIR/memory/templates" "$PACK_DIR/memory/templates"
cp "$REPO_DIR/WORKFLOW.md" "$PACK_DIR/WORKFLOW.md"
PACK_DIR_DISP="$(win_path "$PACK_DIR")"
echo "[claude-harness] pack files synced to $PACK_DIR"

MEMORY_LINE="Memory spec (session checkpoints + mistake-memory; hooks are spec-only, not shipped yet): \`$PACK_DIR_DISP/memory/SPEC.md\`"
if [ "$WITH_MEMORY_HOOKS" -eq 1 ]; then
  rm -rf "$PACK_DIR/memory/hooks"
  cp -r "$REPO_DIR/memory/hooks" "$PACK_DIR/memory/hooks"
  echo "[claude-harness] memory hooks installed at $PACK_DIR/memory/hooks (not wired into settings.json — see instructions below)"
  MEMORY_LINE="Memory spec + hooks (session checkpoints — opt-in, installed): \`$PACK_DIR_DISP/memory/SPEC.md\`, \`$PACK_DIR_DISP/memory/hooks/\`"
  cat <<EOF
[claude-harness] Add this to ~/.claude/settings.json under "hooks" (MERGE into
existing arrays — e.g. your SessionStart array already has other hooks,
append to it, don't replace it):
  "SessionStart": [{ "hooks": [{ "type": "command", "command": "node \"$PACK_DIR_DISP/memory/hooks/memory-init.js\"", "timeout": 5 }] }]
  "PostToolUse":  [{ "matcher": "Edit|Write", "hooks": [{ "type": "command", "command": "node \"$PACK_DIR_DISP/memory/hooks/memory-checkpoint.js\"", "timeout": 5 }] }]
  "PreCompact":   [{ "hooks": [{ "type": "command", "command": "node \"$PACK_DIR_DISP/memory/hooks/memory-compact.js\"", "timeout": 5 }] }]
  "SessionEnd":   [{ "hooks": [{ "type": "command", "command": "node \"$PACK_DIR_DISP/memory/hooks/memory-flush.js\"", "timeout": 5 }] }]
Opt-in for a reason — new code, low-volume real-world testing so far. See memory/SPEC.md.
EOF
elif [ -d "$PACK_DIR/memory/hooks" ]; then
  echo "[claude-harness] memory hooks already present at $PACK_DIR/memory/hooks (left in place — re-run with --with-memory-hooks to refresh)"
  MEMORY_LINE="Memory spec + hooks (session checkpoints — opt-in, installed): \`$PACK_DIR_DISP/memory/SPEC.md\`, \`$PACK_DIR_DISP/memory/hooks/\`"
else
  echo "[claude-harness] memory hooks NOT installed (default). Re-run with --with-memory-hooks to add them."
fi

# --- 2. Statusline: dictated path, safe to copy directly ---
mkdir -p "$CLAUDE_DIR"
if [ ! -f "$CLAUDE_DIR/statusline.sh" ] || ! cmp -s "$REPO_DIR/statusline/statusline.sh" "$CLAUDE_DIR/statusline.sh"; then
  cp "$REPO_DIR/statusline/statusline.sh" "$CLAUDE_DIR/statusline.sh"
  chmod +x "$CLAUDE_DIR/statusline.sh"
  echo "[claude-harness] statusline.sh installed/updated at $CLAUDE_DIR/statusline.sh"
else
  echo "[claude-harness] statusline.sh already up to date"
fi

CLAUDE_DIR_DISP="$(win_path "$CLAUDE_DIR")"
if [ -f "$CLAUDE_DIR/settings.json" ] && grep -q '"statusLine"' "$CLAUDE_DIR/settings.json"; then
  echo "[claude-harness] settings.json already has a statusLine block — leaving it alone"
else
  cat <<EOF
[claude-harness] settings.json has no statusLine block. Add manually (see statusline/README.md):
  "statusLine": { "type": "command", "command": "bash \"$CLAUDE_DIR_DISP/statusline.sh\"", "refreshInterval": 60 }
EOF
fi

# --- 3. Managed pointer block in CLAUDE.md (Claude Code's always-loaded file) ---
# Does NOT copy security-invariants.md verbatim: if your CLAUDE.md already has
# hand-written security rules, dedupe them against rules/security-invariants.md
# yourself first — this installer never overwrites your prose, only its own
# marked block.
COMMIT="$(cd "$REPO_DIR" && git rev-parse --short HEAD 2>/dev/null || echo unknown)"
BLOCK_FILE="$(mktemp)"
{
  echo "$MARKER_START"
  echo "## Claude Harness (installed from $REPO_DIR @ $COMMIT)"
  echo
  echo "- Security invariants (always-on, every session/surface — read this alongside this file): \`$PACK_DIR_DISP/rules/security-invariants.md\`"
  echo "- Engineering rules (YAGNI ladder, debugging, review, deps, perf, commit lifecycle): \`$PACK_DIR_DISP/rules/engineering.md\`"
  echo "- Design lane (triggered on UI/UX task shape): \`$PACK_DIR_DISP/rules/design-lane.md\`"
  echo "- Skills manifest (install/version source of truth): \`$PACK_DIR_DISP/skills/manifest.yaml\`"
  echo "- $MEMORY_LINE"
  echo "- Workflow loop (Understand -> Plan -> Build -> Verify -> Security-if-needed): \`$PACK_DIR_DISP/WORKFLOW.md\`"
  echo "$MARKER_END"
} > "$BLOCK_FILE"

touch "$CLAUDE_MD"
cp "$CLAUDE_MD" "$CLAUDE_MD.bak.$(date +%Y%m%d%H%M%S)"

if grep -qF "$MARKER_START" "$CLAUDE_MD"; then
  TMP="$(mktemp)"
  awk -v start="$MARKER_START" -v end="$MARKER_END" -v blockfile="$BLOCK_FILE" '
    $0 == start { while ((getline line < blockfile) > 0) print line; skip=1; next }
    $0 == end { skip=0; next }
    skip { next }
    { print }
  ' "$CLAUDE_MD" > "$TMP"
  mv "$TMP" "$CLAUDE_MD"
  echo "[claude-harness] updated managed block in $CLAUDE_MD"
else
  { cat "$CLAUDE_MD"; echo; cat "$BLOCK_FILE"; } > "$CLAUDE_MD.new"
  mv "$CLAUDE_MD.new" "$CLAUDE_MD"
  echo "[claude-harness] appended managed block to $CLAUDE_MD"
fi
rm -f "$BLOCK_FILE"

echo "[claude-harness] done. Pack: $PACK_DIR_DISP | Managed block: $(win_path "$CLAUDE_DIR")/CLAUDE.md"
