#!/usr/bin/env bash
# Installs the Claude Harness rules/skills/memory pack + statusline into
# ~/.claude. Idempotent — safe to re-run after `git pull`.
#
# Usage: ./install.sh [--with-memory-hooks] [--check]
#   --with-memory-hooks   Also install the session-checkpoint hooks (see
#                          memory/SPEC.md). Opt-in, default off: these fire on
#                          every single Edit/Write once wired, and this
#                          installer never auto-edits settings.json — you
#                          paste the printed hook config in yourself. Once
#                          installed with this flag, a later plain `./install.sh`
#                          (no flag) does NOT remove them — there is no
#                          implicit uninstall.
#   --check                Report-only drift check: diffs the installed pack
#                          (~/.claude/claude-harness/) against this repo's
#                          current source, one file/dir at a time. Prints any
#                          mismatches and exits 1 if drift is found, exits 0 if
#                          the pack matches exactly. Never writes anything —
#                          catches the case where the pack fell out of sync
#                          with the repo (e.g. install.sh ran against a dirty
#                          worktree, or the pack was edited directly) without
#                          mutating ~/.claude/CLAUDE.md the way a real install
#                          run would. Exits before any install step runs.
set -euo pipefail

WITH_MEMORY_HOOKS=0
CHECK_MODE=0
for arg in "$@"; do
  case "$arg" in
    --with-memory-hooks) WITH_MEMORY_HOOKS=1 ;;
    --check) CHECK_MODE=1 ;;
  esac
done

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLAUDE_DIR="${CLAUDE_HARNESS_TARGET:-$HOME/.claude}"
PACK_DIR="$CLAUDE_DIR/claude-harness"
CLAUDE_MD="$CLAUDE_DIR/CLAUDE.md"

# --- --check: report-only drift check, exits before any install step runs ---
if [ "$CHECK_MODE" -eq 1 ]; then
  echo "[claude-harness] --check: diffing installed pack ($PACK_DIR) against source ($REPO_DIR)"
  DRIFT=0
  check_path() {
    local rel="$1"
    if [ ! -e "$PACK_DIR/$rel" ]; then
      echo "[claude-harness] MISSING: $rel not installed"
      DRIFT=1
      return
    fi
    local tmp
    tmp="$(mktemp)"
    if ! diff -rq "$REPO_DIR/$rel" "$PACK_DIR/$rel" >"$tmp" 2>&1; then
      cat "$tmp"
      DRIFT=1
    fi
    rm -f "$tmp"
  }
  for rel in rules skills memory/SPEC.md memory/templates caveman WORKFLOW.md; do
    check_path "$rel"
  done
  # memory/hooks is opt-in (--with-memory-hooks) — only check it if it was
  # actually installed; its absence is expected default state, not drift.
  if [ -d "$PACK_DIR/memory/hooks" ]; then
    check_path "memory/hooks"
  fi
  if [ "$DRIFT" -eq 0 ]; then
    echo "[claude-harness] pack matches source exactly — no drift"
    exit 0
  else
    echo "[claude-harness] drift found — re-run ./install.sh (without --check) to sync"
    exit 1
  fi
fi

# On Git Bash, $HOME/PACK_DIR/etc. are POSIX-style (/c/Users/...). That's fine
# for this script's own file operations, but any path we WRITE into CLAUDE.md
# or print as a settings.json snippet is consumed by native node.exe / Claude
# Code itself, which does not understand /c/... paths (confirmed directly:
# native node.exe fails "Cannot find module" on a POSIX-style require path).
# Use drive-letter form for everything user-facing/machine-facing; falls back
# to the original path unchanged on platforms without `pwd -W` (macOS/Linux,
# where this distinction doesn't exist anyway).
win_path() {
  local p="$1" w
  w=$(cd "$p" 2>/dev/null && pwd -W 2>/dev/null) || true
  if [ -n "$w" ]; then echo "$w"; else echo "$p"; fi
}
MARKER_START="<!-- claude-harness:managed:start (auto-generated by install.sh — do not hand-edit; re-run install.sh to update) -->"
MARKER_END="<!-- claude-harness:managed:end -->"

echo "[claude-harness] installing from $REPO_DIR into $CLAUDE_DIR"

# --- 1. Pack files: namespaced, never touch ~/.claude/skills or ~/.claude/memory directly ---
mkdir -p "$PACK_DIR" "$PACK_DIR/memory"
rm -rf "$PACK_DIR/rules" "$PACK_DIR/skills" "$PACK_DIR/memory/templates"
cp -r "$REPO_DIR/rules" "$PACK_DIR/rules"
cp -r "$REPO_DIR/skills" "$PACK_DIR/skills"
cp "$REPO_DIR/memory/SPEC.md" "$PACK_DIR/memory/SPEC.md"
cp -r "$REPO_DIR/memory/templates" "$PACK_DIR/memory/templates"
cp "$REPO_DIR/WORKFLOW.md" "$PACK_DIR/WORKFLOW.md"
PACK_DIR_DISP="$(win_path "$PACK_DIR")"
echo "[claude-harness] pack files synced to $PACK_DIR"

MEMORY_LINE="Memory spec (session checkpoints + mistake-memory; hooks are spec-only, not shipped yet): \`$PACK_DIR_DISP/memory/SPEC.md\`"
if [ "$WITH_MEMORY_HOOKS" -eq 1 ]; then
  rm -rf "$PACK_DIR/memory/hooks"
  cp -r "$REPO_DIR/memory/hooks" "$PACK_DIR/memory/hooks"
  echo "[claude-harness] memory hooks installed at $PACK_DIR/memory/hooks (not wired into settings.json — see instructions below)"
  MEMORY_LINE="Memory spec + hooks (session checkpoints — opt-in, installed): \`$PACK_DIR_DISP/memory/SPEC.md\`, \`$PACK_DIR_DISP/memory/hooks/\`"
  cat <<EOF
[claude-harness] Add this to ~/.claude/settings.json under "hooks" (MERGE into
existing arrays — e.g. your SessionStart array already has other hooks,
append to it, don't replace it):
  "SessionStart":     [{ "hooks": [{ "type": "command", "command": "node \"$PACK_DIR_DISP/memory/hooks/memory-init.js\"", "timeout": 5 }] }]
  "UserPromptSubmit": [{ "hooks": [{ "type": "command", "command": "node \"$PACK_DIR_DISP/memory/hooks/memory-recall.js\"", "timeout": 5 }] }]
  "PostToolUse":      [{ "matcher": "Edit|Write", "hooks": [{ "type": "command", "command": "node \"$PACK_DIR_DISP/memory/hooks/memory-checkpoint.js\"", "timeout": 5 }] },
                        { "matcher": "Read|Edit|Write", "hooks": [{ "type": "command", "command": "node \"$PACK_DIR_DISP/memory/hooks/memory-architecture.js\"", "timeout": 5 }] }]
  "PreCompact":       [{ "hooks": [{ "type": "command", "command": "node \"$PACK_DIR_DISP/memory/hooks/memory-compact.js\"", "timeout": 5 }] }]
  "SessionEnd":       [{ "hooks": [{ "type": "command", "command": "node \"$PACK_DIR_DISP/memory/hooks/memory-flush.js\"", "timeout": 5 }] }]
memory-recall.js and memory-architecture.js implement project-architecture
memory (memory/SPEC.md's "Project-architecture memory" section) -- mechanical
keyword recall on every prompt + file-touch recall/staleness-flagging on every
Read/Edit/Write. Note memory-recall.js's UserPromptSubmit registration is a
SEPARATE array entry from caveman's own UserPromptSubmit hook below -- Claude
Code runs all matching hooks for an event, this does not replace that one.
Opt-in for a reason — new code, low-volume real-world testing so far. See memory/SPEC.md.
EOF
elif [ -d "$PACK_DIR/memory/hooks" ]; then
  echo "[claude-harness] memory hooks already present at $PACK_DIR/memory/hooks (left in place — re-run with --with-memory-hooks to refresh)"
  MEMORY_LINE="Memory spec + hooks (session checkpoints — opt-in, installed): \`$PACK_DIR_DISP/memory/SPEC.md\`, \`$PACK_DIR_DISP/memory/hooks/\`"
else
  echo "[claude-harness] memory hooks NOT installed (default). Re-run with --with-memory-hooks to add them."
fi

# --- 1b. Caveman ultra: default-on communication style, always installed ---
# Not opt-in like memory hooks -- this is the harness's baseline communication
# mode. Ships the hook pair (SessionStart ruleset injection + UserPromptSubmit
# per-turn reinforcement) plus its config resolver and skill source, and seeds
# the default-mode config file to "ultra" if the user has no config yet.
# Existing user config/flag state is never overwritten -- this only sets a
# default where none exists, same idempotence contract as the rest of this
# script.
rm -rf "$PACK_DIR/caveman"
cp -r "$REPO_DIR/caveman" "$PACK_DIR/caveman"
echo "[claude-harness] caveman hooks synced to $PACK_DIR/caveman"

CAVEMAN_CONFIG_DIR="${XDG_CONFIG_HOME:-}"
if [ -n "$CAVEMAN_CONFIG_DIR" ]; then
  CAVEMAN_CONFIG_DIR="$CAVEMAN_CONFIG_DIR/caveman"
elif [ -n "${APPDATA:-}" ]; then
  CAVEMAN_CONFIG_DIR="$APPDATA/caveman"
else
  CAVEMAN_CONFIG_DIR="$HOME/.config/caveman"
fi
CAVEMAN_CONFIG_DIR="${CAVEMAN_CONFIG_DIR//\\//}"
CAVEMAN_CONFIG_FILE="$CAVEMAN_CONFIG_DIR/config.json"
if [ ! -f "$CAVEMAN_CONFIG_FILE" ]; then
  mkdir -p "$CAVEMAN_CONFIG_DIR"
  echo '{ "defaultMode": "ultra" }' > "$CAVEMAN_CONFIG_FILE"
  echo "[claude-harness] caveman default mode set to ultra at $CAVEMAN_CONFIG_FILE"
else
  echo "[claude-harness] caveman config already exists at $CAVEMAN_CONFIG_FILE — left as-is"
fi

PACK_DIR_DISP_PRE="$(win_path "$PACK_DIR")"
if [ -f "$CLAUDE_DIR/settings.json" ] && grep -q 'caveman-activate.js' "$CLAUDE_DIR/settings.json"; then
  echo "[claude-harness] caveman hooks already wired in settings.json"
else
  cat <<EOF
[claude-harness] Add this to ~/.claude/settings.json under "hooks" (MERGE into
existing arrays, don't replace them):
  "SessionStart":     [{ "hooks": [{ "type": "command", "command": "node \"$PACK_DIR_DISP_PRE/caveman/hooks/caveman-activate.js\"", "timeout": 5 }] }]
  "UserPromptSubmit": [{ "hooks": [{ "type": "command", "command": "node \"$PACK_DIR_DISP_PRE/caveman/hooks/caveman-mode-tracker.js\"", "timeout": 5 }] }]
Without this, the default-mode config above is inert -- these two hooks are what
actually inject the ruleset and reinforce it every turn. Override anytime by
saying "stop caveman" / "normal mode" in chat, or editing $CAVEMAN_CONFIG_FILE.
EOF
fi

# --- 2. Statusline: dictated path, safe to copy directly ---
mkdir -p "$CLAUDE_DIR"
if [ ! -f "$CLAUDE_DIR/statusline.sh" ] || ! cmp -s "$REPO_DIR/statusline/statusline.sh" "$CLAUDE_DIR/statusline.sh"; then
  cp "$REPO_DIR/statusline/statusline.sh" "$CLAUDE_DIR/statusline.sh"
  chmod +x "$CLAUDE_DIR/statusline.sh"
  echo "[claude-harness] statusline.sh installed/updated at $CLAUDE_DIR/statusline.sh"
else
  echo "[claude-harness] statusline.sh already up to date"
fi

CLAUDE_DIR_DISP="$(win_path "$CLAUDE_DIR")"
if [ -f "$CLAUDE_DIR/settings.json" ] && grep -q '"statusLine"' "$CLAUDE_DIR/settings.json"; then
  echo "[claude-harness] settings.json already has a statusLine block — leaving it alone"
else
  cat <<EOF
[claude-harness] settings.json has no statusLine block. Add manually (see statusline/README.md):
  "statusLine": { "type": "command", "command": "bash \"$CLAUDE_DIR_DISP/statusline.sh\"", "refreshInterval": 60 }
EOF
fi

# --- 3. Managed pointer block in CLAUDE.md (Claude Code's always-loaded file) ---
# Does NOT copy security-invariants.md verbatim: if your CLAUDE.md already has
# hand-written security rules, dedupe them against rules/security-invariants.md
# yourself first — this installer never overwrites your prose, only its own
# marked block.
# A run against a dirty tree stamps CLAUDE.md with a hash that predates
# whatever cp -r just copied a few lines below -- silently wrong provenance,
# not just imprecise (found on this exact repo: caveman/ and
# skills/manifest.yaml were both installed from an uncommitted worktree, then
# committed minutes later, leaving the stamped hash pointing at the prior
# commit). `git describe --dirty` alone isn't enough here -- it only inspects
# tracked-file diffs against the index, so a brand-new UNTRACKED file (e.g. a
# not-yet-`git add`ed skill under rules/ or skills/) would still get copied by
# cp -r while the stamp claims clean. --untracked-files=all catches both.
COMMIT="$(cd "$REPO_DIR" && git rev-parse --short HEAD 2>/dev/null || echo unknown)"
if [ -n "$(cd "$REPO_DIR" && git status --porcelain --untracked-files=all 2>/dev/null)" ]; then
  COMMIT="${COMMIT}-dirty"
fi
BLOCK_FILE="$(mktemp)"
{
  echo "$MARKER_START"
  echo "## Claude Harness (installed from $REPO_DIR @ $COMMIT)"
  echo
  echo "- Security invariants (always-on, every session/surface — read this alongside this file): \`$PACK_DIR_DISP/rules/security-invariants.md\`"
  echo "- Engineering rules (YAGNI ladder, debugging, review, deps, perf, commit lifecycle): \`$PACK_DIR_DISP/rules/engineering.md\`"
  echo "- Design lane (triggered on UI/UX task shape): \`$PACK_DIR_DISP/rules/design-lane.md\`"
  echo "- Skills manifest (install/version source of truth): \`$PACK_DIR_DISP/skills/manifest.yaml\`"
  echo "- Communication default (caveman ultra, always-on unless you say \"stop caveman\"/\"normal mode\"): \`$PACK_DIR_DISP/caveman/skills/caveman/SKILL.md\`, config \`$CAVEMAN_CONFIG_FILE\`"
  echo "- $MEMORY_LINE"
  echo "- Workflow loop (Understand -> Plan -> Build -> Verify -> Security-if-needed): \`$PACK_DIR_DISP/WORKFLOW.md\`"
  echo "$MARKER_END"
} > "$BLOCK_FILE"

touch "$CLAUDE_MD"
cp "$CLAUDE_MD" "$CLAUDE_MD.bak.$(date +%Y%m%d%H%M%S)"

if grep -qF "$MARKER_START" "$CLAUDE_MD"; then
  TMP="$(mktemp)"
  awk -v start="$MARKER_START" -v end="$MARKER_END" -v blockfile="$BLOCK_FILE" '
    $0 == start { while ((getline line < blockfile) > 0) print line; skip=1; next }
    $0 == end { skip=0; next }
    skip { next }
    { print }
  ' "$CLAUDE_MD" > "$TMP"
  mv "$TMP" "$CLAUDE_MD"
  echo "[claude-harness] updated managed block in $CLAUDE_MD"
else
  { cat "$CLAUDE_MD"; echo; cat "$BLOCK_FILE"; } > "$CLAUDE_MD.new"
  mv "$CLAUDE_MD.new" "$CLAUDE_MD"
  echo "[claude-harness] appended managed block to $CLAUDE_MD"
fi
rm -f "$BLOCK_FILE"

echo "[claude-harness] done. Pack: $PACK_DIR_DISP | Managed block: $(win_path "$CLAUDE_DIR")/CLAUDE.md"
